-- Renovate dashboard: per-user GitHub identity and the set of repositories each user has
-- chosen to track. Only the selection is persisted; repo contents are fetched live from GitHub.

CREATE TABLE app_user (
    -- GitHub's numeric user id (stable, globally unique) is used directly as the primary key.
    id         BIGINT       NOT NULL PRIMARY KEY,
    login      VARCHAR(255) NOT NULL,
    name       VARCHAR(255),
    avatar_url VARCHAR(1024),
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE enabled_repo (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    repo_full_name VARCHAR(512) NOT NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_enabled_repo_user_repo UNIQUE (user_id, repo_full_name)
);

CREATE INDEX idx_enabled_repo_user_id ON enabled_repo (user_id);
