-- Generalise the per-user identity from "GitHub numeric id is the primary key" to a surrogate
-- primary key plus a (provider, provider_user_id) business identity, so users from multiple OAuth
-- providers (GitHub, GitLab, ...) can coexist without their provider ids colliding.
--
-- Existing rows are GitHub users: their current id stays the primary key (so enabled_repo.user_id
-- keeps pointing at the same row, no foreign-key remap needed), their provider is backfilled to
-- 'github', and their provider_user_id is backfilled from that GitHub numeric id. New rows get a
-- surrogate id from an identity sequence that starts safely above every existing id.

ALTER TABLE app_user ADD COLUMN provider VARCHAR(32);
ALTER TABLE app_user ADD COLUMN provider_user_id VARCHAR(255);

UPDATE app_user SET provider = 'github' WHERE provider IS NULL;
UPDATE app_user SET provider_user_id = CAST(id AS VARCHAR) WHERE provider_user_id IS NULL;

ALTER TABLE app_user ALTER COLUMN provider SET NOT NULL;
ALTER TABLE app_user ALTER COLUMN provider_user_id SET NOT NULL;

ALTER TABLE app_user
    ADD CONSTRAINT uq_app_user_provider_user UNIQUE (provider, provider_user_id);

-- Turn the id column into a DB-generated identity for new inserts. Existing rows keep their values;
-- the sequence starts above the current maximum so a freshly minted surrogate id can never collide
-- with an existing (formerly GitHub-derived) one.
DO $$
DECLARE
    next_id BIGINT;
BEGIN
    SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM app_user;
    EXECUTE format(
        'ALTER TABLE app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
        next_id);
END $$;
