---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: start-renovate-deepseek-secret
  namespace: default
spec:
  encryptedData:
    deepseek.api-key: AgByyPdNzu9hV+HCt5SsQ5vWddh0+7mUO9snfFqlohvDbJB+dko6Ky46nCv1aXxiKUVyBYHcRvBKK8Hev4J1LPxD3WqfcSwlR6uQWXR+4tQYG/WjaewrZD5zp5FabvgDVYYBeX26Zk+x3Y8TLUW9cYgPLqw7fVOHNsWcTDttFH/sQDRYczyS7MsyfuKCtkKDBy3snX1fJP6aWsD7zOjr/4Jx612Mfda58hHttqEnfmx+TcNkAsvOaBHn0B1oimviWwLwbM4/RkzpUlBMZoRuVQQtIlST5v/ahEJX8UhmjOkSyrR3Zp2y6xndbjCsZbMtWmpl/rCVLnWpCRyb+02KsaDzWE+7XFhGC7RpmluGQQAv1/crjR79ZHg2ZxKl2IU2rULGQYXVDVKBtqOjX6VIIs1PHSwe43xVYQaGT7EXl15NzATIpqd6TVjru1QpvWhHOc4RX8Lj2zmflIyPQObU3zCHi6nXdscP4VqdUwdbAjCmXeLv2L6oNZIMcBZh6UR00hHJ+wkBJBWCXwOVmoC2E2PNH9YP+hPro6hwNjgCF7RI2+gSBdQp10+JaMKdYgA3nuxsEyelNiYfcVqchnU1KkzNbJkUKvz//0k3owsuUhkst1MenAmk7B8ZRWPx3ur+ZgGAefgBm1UaRn+ldfNAOK7cwlgzLw0Ja8+thcF00opKaJ6U4QP3aCs5aIU0OiXeEfiWGfQH+h0dAQ5HtTFSM4VhIcNqDCHhVSD+DSQ87A+wQ1C7yA==
  template:
    metadata:
      name: start-renovate-deepseek-secret
      namespace: default
